//****************************************************************************************************************************************************
// {W_t} by {H_t} systolic array sub_placer autogenerated by rtl_gen.py


module sub_placer_{ty}(input wire clk,
                       input wire rst,
                       output wire complete,
                       input wire  [BUS_WIDTH-1:0] completed_sum,
                       output wire [BUS_WIDTH-1:0] partial_sum_out,

                       input wire load_enable_in,
                       output wire load_enable_out,
                       input wire  [BUS_WIDTH-1:0] load_pipe_in,
                       output wire  [BUS_WIDTH-1:0] load_pipe_out,

                       input wire  [BUS_WIDTH-1:0] unload_pipe_in,
                       output wire [BUS_WIDTH-1:0] unload_pipe_out);
    
    //********************************************************
    // parameters for the entire placer

    parameter integer N = -1;
    parameter integer T = -1;
    parameter integer D = -1;
    parameter integer B = -1;
    parameter integer V = -1;
    parameter integer MAX_K = -1;
    parameter integer P = -1;

    parameter integer MSAD = -1;                // Maximum Sub-Array Depth
    parameter integer WSRD = -1;                // worst sum return depth, the number of cycles for a newly computed sum to arrive at the input of the farthest PE across all sub-arrays.    
    parameter integer RAM_CYCLES = -1;          // should be set to 1
    parameter integer MULT_CYCLES = -1;         // should be set to 0 for now
    parameter integer FIXED_SUM_CYCLES = -1;    // should be set to 1
    parameter integer SCD = -1;

    parameter integer BUS_WIDTH = -1;
    parameter integer MAX_NUM_OF_UPDATES = -1;
    parameter integer MAX_SWAPS_PER_UPDATE = -1;
    
    //********************************************************
    // parameters for this sub-array

    parameter integer BLK_ID_OFFSET = {blk_id_offset};       // Converts local blk_id to global blk_id

    parameter integer W_t = {W_t};
    parameter integer H_t = {H_t};
    parameter integer B_t = {B_t};
    parameter integer R_t = {R_t};
    
    //************************************************************************************************************************************************
    // Systolic Array:
{pe_array}
    //************************************************************************************************************************************************
    // Summing Tree:

{summing_tree}
endmodule