#######################################################################################################
class Arch_info:
        
    def __init__(self,filename):

        # A map of types to max possible fanin of that type
        self.arch_types_to_fanin = {}
        ###############################################################################################
        # Read in systolic_arch_info, which was generated by VTR
        with open(filename,"r") as f:

            header = f.readline()
            for line in f:
                line = line.split()
                
                ty = line[0]
                fanin = int(line[1])

                self.arch_types_to_fanin[ty] = fanin
#######################################################################################################