import log
import random
import argparse
import grid_info as gi
###################################################################################################
def main():
    description = 'Creates a placer_init file with random placement, from a systolic_grid_info file'
    p = argparse.ArgumentParser(description = description)
    p.add_argument("systolic_grid_info",help="systolic_grid_info input file")
    p.add_argument("placer_init",help="placer_init output file")
    args = p.parse_args()
    ###############################################################################################
    # Read in systolic_grid_info, which was generated by VTR
    log.blue("[Reading systolic_grid_info]")
    grid_info = gi.Grid_info(args.systolic_grid_info)
    for ty in grid_info.grid_types:
        log.blue("[{} width {}]".format(ty,grid_info.grid[ty].width))
        log.blue("[{} height {}]".format(ty,grid_info.grid[ty].height))
    ###############################################################################################
    # Write out placer_init
    log.blue("[Writing placer_init]")
    with open(args.placer_init,"w") as f:
        f.write("type cx cy seed id\n")

        for ty in grid_info.grid_types:
            n = (grid_info.grid[ty].width) * (grid_info.grid[ty].height)
            blk_ids = list(range(n))
            random.shuffle(blk_ids)

            for cx in range(grid_info.grid[ty].width):
                for cy in range(grid_info.grid[ty].height):
                    seed = random.randint(1,65535)
                    f.write("{} {} {} {} {}\n".format(ty, cx,cy,seed,blk_ids.pop()))
    ###############################################################################################
if __name__ == "__main__":
    main()