import math
from loc import *
#######################################################################################################
# Note: Classes Grid and Grid_info assume that the systolic_grid_info file
#       only describes a rectangular region
#######################################################################################################
class Grid:
    def __init__(self):
        self.width = None
        self.height = None
        self.pe_loc_to_blk_loc = {}
        self.max_cx = -1
        self.max_cy = -1

    def get_home_pe_coords(self,blk_id):
        row = math.floor(blk_id/self.width)
        col = (blk_id%self.width)
        if(row % 2 != 0):
            col = (self.width - 1) - (blk_id%self.width)
        return PE_Loc(col,row)
    
    def get_home_blk_id(self,pe_loc):
        row = pe_loc.y
        col = pe_loc.x
        home_id = row*self.width
        if(row % 2 == 0):
            home_id += col
        else:
            home_id += (self.width - 1) - col
        return home_id

#######################################################################################################
class Grid_info:
        
    def __init__(self,filename):

        self.grid_types = set()

        self.total_width = None
        self.total_height = None

        self.grid = {}
        ###############################################################################################
        # Read in systolic_grid_info, which was generated by VTR
        with open(filename,"r") as f:

            line = f.readline().split()
            self.total_width = int(line[0])
            self.total_height = int(line[2])
            header = f.readline()

            max_cx = {}
            max_cy = {}

            for line in f:
                line = line.split()
                ty = line[0]
                cx, cy, x, y = list(map(int,line[1:]))
                if ty not in self.grid_types:
                    self.grid_types.add(ty)
                    self.grid[ty] = Grid()
                    max_cx[ty] = -1
                    max_cy[ty] = -1

                pe_loc = PE_Loc(cx,cy)
                blk_loc = BLK_Loc(x,y)
                self.grid[ty].pe_loc_to_blk_loc[pe_loc] = blk_loc

                max_cx[ty] = max(max_cx[ty],cx)
                max_cy[ty] = max(max_cy[ty],cy)

            for ty in self.grid_types:
                self.grid[ty].width = max_cx[ty] + 1
                self.grid[ty].height = max_cy[ty] + 1
#######################################################################################################